export const charList = [
    {id: 0, name:"Android 16", img:"/images/Android16.png?url"},
    {id: 1, name:"Android 17", img:"/images/Android17.png?url"},
    {id: 2, name:"Android 18", img:"/images/Android18.jpg?url"},
    {id: 3, name:"Bulma", img:"/images/Bulma.png"},
    {id: 4, name:"Cell", img:"/images/Cell.png"},
    {id: 5, name:"Chiaotzu", img:"/images/Chiaotzu.png"},
    {id: 6, name:"Chi Chi", img:"/images/Chichi.png"},
    {id: 7, name:"Gohan", img:"/images/Gohan.png"},
    {id: 8, name:"Goku", img:"/images/Goku.png"},
    {id: 9, name:"Kami-sama", img:"/images/Kami-sama.png"},
    {id: 10, name:"Korin", img:"/images/Korin.png"},
    {id: 11, name:"Krillin", img:"/images/Krillin.png"},
    {id: 12, name:"Piccolo", img:"/images/Piccolo.png"},
    {id: 13, name:"Popo", img:"/images/Popo.png"},
    {id: 14, name:"Roshi", img:"/images/Roshi.jpg"},
    {id: 15, name:"Tien Shinhan", img:"/images/TienShinhan.png"},
    {id: 16, name:"Trunks", img:"/images/Trunks.png"},
    {id: 17, name:"Vegeta", img:"/images/Vegeta.png"},
    {id: 18, name:"Yajirobe", img:"/images/Yajirobe.png"},
    {id: 19, name:"Yamcha", img:"/images/Yamcha.png"},
]