export const charList = [
    {id: 0, name:"Android 16", img:"/src/assets/Android16.png"},
    {id: 1, name:"Android 17", img:"/src/assets/Android17.png"},
    {id: 2, name:"Android 18", img:"/src/assets/Android18.jpg"},
    {id: 3, name:"Bulma", img:"/src/assets/Bulma.png"},
    {id: 4, name:"Cell", img:"/src/assets/Cell.png"},
    {id: 5, name:"Chiaotzu", img:"/src/assets/Chiaotzu.png"},
    {id: 6, name:"Chi Chi", img:"/src/assets/Chichi.png"},
    {id: 7, name:"Gohan", img:"/src/assets/Gohan.png"},
    {id: 8, name:"Goku", img:"/src/assets/Goku.png"},
    {id: 9, name:"Kami-sama", img:"/src/assets/Kami-sama.png"},
    {id: 10, name:"Korin", img:"/src/assets/Korin.png"},
    {id: 11, name:"Krillin", img:"/src/assets/Krillin.png"},
    {id: 12, name:"Piccolo", img:"/src/assets/Piccolo.png"},
    {id: 13, name:"Popo", img:"/src/assets/Popo.png"},
    {id: 14, name:"Roshi", img:"/src/assets/Roshi.jpg"},
    {id: 15, name:"Tien Shinhan", img:"/src/assets/TienShinhan.png"},
    {id: 16, name:"Trunks", img:"/src/assets/Trunks.png"},
    {id: 17, name:"Vegeta", img:"/src/assets/Vegeta.png"},
    {id: 18, name:"Yajirobe", img:"/src/assets/Yajirobe.png"},
    {id: 19, name:"Yamcha", img:"/src/assets/Yamcha.png"},
]